services:
  db:
    image: postgres:16.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: moviesapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
  backend:
    build: /backend
    command: npm run start:prod
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data:
